"""
Copilot router — streams Claude responses via Server-Sent Events,
generates structured investment memos, and persists conversations so
agents can reopen past analyses from a history sidebar.
"""
import json
import uuid
from datetime import datetime, timezone
from typing import AsyncGenerator

import anthropic
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from sqlalchemy import desc, select
from sqlalchemy.ext.asyncio import AsyncSession

from ..auth import get_current_user
from ..config import get_settings
from ..database import get_db
from ..models.copilot_conversation import CopilotConversation
from ..models.user import User
from ..schemas import CamelModel
from ..services import property_service

router = APIRouter(prefix="/copilot")

_SYSTEM_BASE = """You are STRATA Copilot, an AI real estate intelligence assistant.
You help investors, agents, and buyers make better real estate decisions.

Rules you must follow:
- All financial figures are estimates, not investment advice
- Every specific claim about a property must reference the data provided
- If asked about data not in your context, say you don't have it — never fabricate numbers
- Add confidence labels to all projections
- Never recommend a specific investment without qualifying assumptions
- When a property is in context, ground every answer in that data"""

_PROPERTY_CONTEXT_TEMPLATE = """
Property in context:
Address: {address}
Price: {price}
Beds/Baths/Sqft: {beds}/{baths}/{sqft}
Deal Score: {deal_score}
Risk Score: {risk_score}
Cap Rate: {cap_rate}%
Est. Cash Flow: ${cash_flow}/mo
Fair Value Range: ${fair_value_low} - ${fair_value_high}
Rent Estimate: ${rent_est_mid}/mo ({rent_confidence} confidence)
Risk Flags: {risk_flags}
Market Regime: {market_regime}
"""

_MEMO_SYSTEM = """You are a professional real estate investment analyst.
Generate a concise, professional investment memo for the property provided.
Be specific — use the actual numbers. Do not pad with generic real estate advice.
Format each section as 2-4 tight paragraphs.
Tone: institutional, direct, no marketing language.

Return ONLY a JSON object with these exact keys:
{
  "title": "Investment Memo — [address]",
  "executiveSummary": "...",
  "propertyOverview": "...",
  "marketContext": "...",
  "financialAnalysis": "...",
  "riskAssessment": "...",
  "recommendation": "Buy | Negotiate | Watch | Avoid",
  "disclaimer": "This memo is generated by STRATA AI and is for informational purposes only. It does not constitute investment advice. Verify all figures independently before making any investment decision."
}"""


class ChatMessage(BaseModel):
    role: str
    content: str


class ChatRequest(BaseModel):
    messages: list[ChatMessage]
    property_id: str | None = None


class MemoRequest(BaseModel):
    property_id: str
    scenario_id: str | None = None
    user_preferences: dict | None = None


async def _stream_sse(chunks: AsyncGenerator[str, None]):
    async for text in chunks:
        yield f"data: {json.dumps({'text': text})}\n\n"
    yield "data: [DONE]\n\n"


@router.post("/chat")
async def chat(body: ChatRequest):
    settings = get_settings()
    if not settings.anthropic_api_key:
        raise HTTPException(status_code=503, detail="Anthropic API key not configured")

    system_prompt = _SYSTEM_BASE

    if body.property_id:
        prop = next(
            (p for p in property_service.MOCK_PROPERTIES if p["id"] == body.property_id),
            None,
        )
        if prop:
            flags = ", ".join(f["label"] for f in prop.get("risk_flags", [])) or "None"
            system_prompt = (
                _PROPERTY_CONTEXT_TEMPLATE.format(
                    address=prop["address"],
                    price=f"{prop['price']:,}",
                    beds=prop["beds"],
                    baths=prop["baths"],
                    sqft=f"{prop['sqft']:,}",
                    deal_score=prop["deal_score"],
                    risk_score=prop["risk_score"],
                    cap_rate=prop["cap_rate"],
                    cash_flow=prop["cash_flow"],
                    fair_value_low=f"{prop['fair_value_low']:,}",
                    fair_value_high=f"{prop['fair_value_high']:,}",
                    rent_est_mid=f"{prop['rent_est_mid']:,}",
                    rent_confidence=prop["rent_confidence"],
                    risk_flags=flags,
                    market_regime=prop.get("market_regime", "Unknown"),
                )
                + "\n\n"
                + _SYSTEM_BASE
            )

    messages = [{"role": m.role, "content": m.content} for m in body.messages]

    async def generate():
        client = anthropic.AsyncAnthropic(api_key=settings.anthropic_api_key)
        async with client.messages.stream(
            model="claude-sonnet-4-20250514",
            max_tokens=1024,
            system=system_prompt,
            messages=messages,
        ) as stream:
            async for text in stream.text_stream:
                yield text

    return StreamingResponse(
        _stream_sse(generate()),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )


@router.post("/generate-memo")
async def generate_memo(body: MemoRequest):
    settings = get_settings()
    if not settings.anthropic_api_key:
        raise HTTPException(status_code=503, detail="Anthropic API key not configured")

    prop = next(
        (p for p in property_service.MOCK_PROPERTIES if p["id"] == body.property_id),
        None,
    )
    if not prop:
        raise HTTPException(status_code=404, detail="Property not found")

    flags = ", ".join(f["label"] for f in prop.get("risk_flags", [])) or "None"
    fv_mid = (prop["fair_value_low"] + prop["fair_value_high"]) / 2
    price_vs_fv = ((prop["price"] - fv_mid) / fv_mid * 100) if fv_mid else 0

    property_context = f"""
Property: {prop["address"]}, {prop["city"]}, {prop["state"]} {prop.get("zip", "")}
List Price: ${prop["price"]:,}
Beds/Baths: {prop["beds"]}bd / {prop["baths"]}ba
Square Feet: {prop["sqft"]:,}
Year Built: {prop.get("year_built", "N/A")}
Property Type: {prop["type"]}
Days on Market: {prop.get("days_on_market", "N/A")}

Investment Metrics:
- Cap Rate: {prop["cap_rate"]}%
- Est. Monthly Cash Flow: ${prop["cash_flow"]:,}/mo
- Cash-on-Cash Return: {prop.get("cash_on_cash", "N/A")}%
- Deal Score: {prop["deal_score"]}/100
- Risk Score: {prop["risk_score"]}/100

Valuation:
- Fair Value Range: ${prop["fair_value_low"]:,} – ${prop["fair_value_high"]:,}
- Price vs. Fair Value: {price_vs_fv:+.1f}%
- Confidence: {prop.get("valuation_confidence", "Medium")}

Rent Estimate:
- Range: ${prop.get("rent_est_low", 0):,} – ${prop.get("rent_est_high", 0):,}/mo
- Mid: ${prop.get("rent_est_mid", 0):,}/mo
- Confidence: {prop.get("rent_confidence", "Medium")}

Market:
- Regime: {prop.get("market_regime", "Balanced")}
- Neighborhood Score: {prop.get("neighborhood_score", "N/A")}/100

Risk Flags: {flags}
"""

    user_message = f"Generate a professional investment memo for this property:\n{property_context}"

    try:
        client = anthropic.AsyncAnthropic(api_key=settings.anthropic_api_key)
        response = await client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=2048,
            system=_MEMO_SYSTEM,
            messages=[{"role": "user", "content": user_message}],
        )

        raw = response.content[0].text.strip()

        # Strip markdown code fences if present
        if raw.startswith("```"):
            raw = raw.split("\n", 1)[1] if "\n" in raw else raw
            raw = raw.rsplit("```", 1)[0].strip()

        memo = json.loads(raw)
        return memo

    except json.JSONDecodeError:
        # Return whatever text Claude sent as executive summary if JSON parse fails
        text = response.content[0].text if "response" in dir() else "Unable to generate memo."
        return {
            "title": f"Investment Memo — {prop['address']}",
            "executiveSummary": text,
            "propertyOverview": "",
            "marketContext": "",
            "financialAnalysis": "",
            "riskAssessment": "",
            "recommendation": "Watch",
            "disclaimer": "This memo is generated by STRATA AI and is for informational purposes only. It does not constitute investment advice. Verify all figures independently before making any investment decision.",
        }
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Claude API error: {exc}")


# ── Conversation history ─────────────────────────────────────────────────────

class ConversationSaveRequest(CamelModel):
    id: str | None = None  # When set, upserts (updates existing); when None, creates
    property_id: str | None = None
    messages: list[ChatMessage]


def _derive_title(messages: list[ChatMessage]) -> str:
    first_user = next((m for m in messages if m.role == "user"), None)
    if not first_user:
        return "New conversation"
    text = first_user.content.strip().replace("\n", " ")
    return text[:80] + ("…" if len(text) > 80 else "")


@router.post("/conversations")
async def save_conversation(
    body: ConversationSaveRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    messages_payload = [{"role": m.role, "content": m.content} for m in body.messages]
    now = datetime.now(timezone.utc)

    if body.id:
        try:
            conv_id = uuid.UUID(body.id)
        except ValueError:
            raise HTTPException(status_code=422, detail="Invalid conversation id")
        result = await db.execute(
            select(CopilotConversation).where(
                CopilotConversation.id == conv_id,
                CopilotConversation.user_id == current_user.id,
            )
        )
        conv = result.scalar_one_or_none()
        if not conv:
            raise HTTPException(status_code=404, detail="Conversation not found")
        conv.messages = messages_payload
        conv.property_id = body.property_id
        conv.title = _derive_title(body.messages)
        conv.updated_at = now
    else:
        conv = CopilotConversation(
            user_id=current_user.id,
            property_id=body.property_id,
            title=_derive_title(body.messages),
            messages=messages_payload,
            created_at=now,
            updated_at=now,
        )
        db.add(conv)

    await db.flush()
    return {
        "id": str(conv.id),
        "title": conv.title,
        "propertyId": conv.property_id,
        "messages": conv.messages,
        "createdAt": conv.created_at.isoformat(),
        "updatedAt": conv.updated_at.isoformat(),
    }


@router.get("/conversations")
async def list_conversations(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    result = await db.execute(
        select(CopilotConversation)
        .where(CopilotConversation.user_id == current_user.id)
        .order_by(desc(CopilotConversation.updated_at))
        .limit(20)
    )
    rows = result.scalars().all()
    return [
        {
            "id": str(r.id),
            "title": r.title or "Untitled",
            "propertyId": r.property_id,
            "messageCount": len(r.messages or []),
            "updatedAt": r.updated_at.isoformat(),
        }
        for r in rows
    ]


@router.get("/conversations/{conv_id}")
async def get_conversation(
    conv_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    result = await db.execute(
        select(CopilotConversation).where(
            CopilotConversation.id == conv_id,
            CopilotConversation.user_id == current_user.id,
        )
    )
    conv = result.scalar_one_or_none()
    if not conv:
        raise HTTPException(status_code=404, detail="Conversation not found")
    return {
        "id": str(conv.id),
        "title": conv.title or "Untitled",
        "propertyId": conv.property_id,
        "messages": conv.messages or [],
        "createdAt": conv.created_at.isoformat(),
        "updatedAt": conv.updated_at.isoformat(),
    }


@router.delete("/conversations/{conv_id}", status_code=204)
async def delete_conversation(
    conv_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    result = await db.execute(
        select(CopilotConversation).where(
            CopilotConversation.id == conv_id,
            CopilotConversation.user_id == current_user.id,
        )
    )
    conv = result.scalar_one_or_none()
    if not conv:
        raise HTTPException(status_code=404, detail="Conversation not found")
    await db.delete(conv)
    await db.flush()
