"""
Reports router — CMA (Comparative Market Analysis) and Property Brief generation.
Both report types are stored in the reports table and accessible via a public GET route.
"""
import json
import logging
import uuid
from datetime import date

import anthropic
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from ..auth import get_current_user
from ..config import get_settings
from ..database import get_db
from ..models.report import Report
from ..models.user import User
from ..services.property_service import MOCK_PROPERTIES

log = logging.getLogger(__name__)

router = APIRouter(prefix="/reports")

_DISCLAIMER = (
    "This report is generated by STRATA AI and is for informational purposes only. "
    "All valuations, rent estimates, and financial projections are estimates based on "
    "available data and should not be construed as investment advice, an appraisal, or "
    "a guarantee of future performance. Verify all figures independently with licensed "
    "professionals before making any real estate decision."
)


# ── helpers ────────────────────────────────────────────────────────────────────

def _get_mock_property(property_id: str) -> dict | None:
    return next((p for p in MOCK_PROPERTIES if p["id"] == property_id), None)


def _recommendation_from_deal_score(deal_score: int) -> str:
    if deal_score >= 70:
        return "Buy"
    if deal_score >= 55:
        return "Negotiate"
    if deal_score >= 40:
        return "Watch"
    return "Avoid"


async def _generate_section_narratives(
    client: anthropic.AsyncAnthropic,
    prop: dict,
    sections: list[str],
) -> dict[str, str]:
    """Generate a narrative for each requested section via Claude."""
    narratives: dict[str, str] = {}

    system = (
        "You are a professional real estate analyst writing a branded CMA report. "
        "Be concise (2-3 paragraphs), factual, and use the provided data. "
        "Avoid generic filler. Tone is professional and institutional."
    )

    flags_text = ", ".join(f["label"] for f in prop.get("risk_flags", [])) or "None identified"
    fv_mid = (prop["fair_value_low"] + prop["fair_value_high"]) / 2
    pvfv = ((prop["price"] - fv_mid) / fv_mid * 100) if fv_mid else 0

    section_prompts: dict[str, str] = {
        "valuation": (
            f"Write a valuation narrative for {prop['address']}, {prop['city']}, {prop['state']}. "
            f"List price: ${prop['price']:,}. Fair value range: ${prop['fair_value_low']:,}–${prop['fair_value_high']:,}. "
            f"Price vs fair value: {pvfv:+.1f}%. Confidence: {prop.get('valuation_confidence', 'Medium')}. "
            f"Cap rate: {prop['cap_rate']}%. Discuss positioning and value relative to comps."
        ),
        "market": (
            f"Write a market conditions narrative for {prop['city']}, {prop['state']}. "
            f"Current market regime: {prop.get('market_regime', 'Balanced')}. "
            f"Neighborhood: {prop.get('neighborhood', 'N/A')}. "
            f"Neighborhood score: {prop.get('neighborhood_score', 'N/A')}/100. "
            f"Discuss supply/demand dynamics, price trends, and what the regime means for buyers."
        ),
        "risk": (
            f"Write a risk assessment narrative for {prop['address']}. "
            f"Composite risk score: {prop['risk_score']}/100 (lower is better). "
            f"Risk flags: {flags_text}. "
            f"Explain each risk factor and its potential financial impact."
        ),
        "financials": (
            f"Write a financial analysis narrative for {prop['address']}. "
            f"Purchase price: ${prop['price']:,}. Cap rate: {prop['cap_rate']}%. "
            f"Estimated monthly cash flow: ${prop['cash_flow']:,}. "
            f"Cash-on-cash: {prop.get('cash_on_cash', 'N/A')}%. "
            f"Rent estimate: ${prop.get('rent_est_mid', 0):,}/mo ({prop.get('rent_confidence', 'Medium')} confidence). "
            f"Analyze investment returns and cash flow sustainability."
        ),
        "neighborhood": (
            f"Write a neighborhood profile for {prop.get('neighborhood', prop['city'])}, {prop['state']}. "
            f"Neighborhood score: {prop.get('neighborhood_score', 'N/A')}/100. "
            f"Market regime: {prop.get('market_regime', 'Balanced')}. "
            f"Describe the area's appeal, demographics, and growth outlook."
        ),
        "comps": (
            f"Write a comparable sales narrative for {prop['address']}, {prop['city']}, {prop['state']}. "
            f"The AVM placed fair value at ${prop['fair_value_low']:,}–${prop['fair_value_high']:,} "
            f"based on recent comparable sales. List price is ${prop['price']:,}. "
            f"Discuss how this property compares to recent sales in the area."
        ),
    }

    for section in sections:
        prompt = section_prompts.get(section)
        if not prompt:
            continue
        try:
            resp = await client.messages.create(
                model="claude-sonnet-4-20250514",
                max_tokens=400,
                system=system,
                messages=[{"role": "user", "content": prompt}],
            )
            narratives[section] = resp.content[0].text.strip()
        except Exception as exc:
            log.warning("Claude narrative error for section %s: %s", section, exc)
            narratives[section] = f"Narrative unavailable. Please review the data manually."

    return narratives


# ── CMA ───────────────────────────────────────────────────────────────────────

class CMARequest(BaseModel):
    property_id: str
    agent_name: str
    agent_email: str
    agent_phone: str
    brokerage_name: str
    client_name: str
    include_sections: list[str] = ["valuation", "comps", "market", "risk", "financials", "neighborhood"]


@router.post("/cma", status_code=201)
async def generate_cma(
    body: CMARequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    settings = get_settings()
    if not settings.anthropic_api_key:
        raise HTTPException(status_code=503, detail="Anthropic API key not configured")

    prop = _get_mock_property(body.property_id)
    if not prop:
        raise HTTPException(status_code=404, detail="Property not found")

    valid_sections = {"valuation", "comps", "market", "risk", "financials", "neighborhood"}
    sections = [s for s in body.include_sections if s in valid_sections]
    if not sections:
        sections = list(valid_sections)

    ai_client = anthropic.AsyncAnthropic(api_key=settings.anthropic_api_key)
    narratives = await _generate_section_narratives(ai_client, prop, sections)

    flags_text = [f["label"] for f in prop.get("risk_flags", [])]
    fv_mid = (prop["fair_value_low"] + prop["fair_value_high"]) / 2
    pvfv = ((prop["price"] - fv_mid) / fv_mid * 100) if fv_mid else 0

    report_id = str(uuid.uuid4())
    content = {
        "reportId": report_id,
        "generatedAt": date.today().isoformat(),
        "agent": {
            "name": body.agent_name,
            "email": body.agent_email,
            "phone": body.agent_phone,
            "brokerage": body.brokerage_name,
        },
        "clientName": body.client_name,
        "property": {
            "id": prop["id"],
            "address": prop["address"],
            "city": prop["city"],
            "state": prop["state"],
            "zip": prop.get("zip", ""),
            "price": prop["price"],
            "beds": prop["beds"],
            "baths": prop["baths"],
            "sqft": prop["sqft"],
            "yearBuilt": prop.get("year_built"),
            "type": prop["type"],
            "dealScore": prop["deal_score"],
            "image": prop.get("image"),
        },
        "sections": {
            "valuation": {
                "narrative": narratives.get("valuation", ""),
                "fairValueLow": prop["fair_value_low"],
                "fairValueHigh": prop["fair_value_high"],
                "confidence": prop.get("valuation_confidence", "Medium"),
                "priceVsFairValue": round(pvfv, 1),
                "compsUsed": 6,
            },
            "comps": {
                "narrative": narratives.get("comps", ""),
            },
            "market": {
                "narrative": narratives.get("market", ""),
                "regime": prop.get("market_regime", "Balanced"),
                "neighborhoodScore": prop.get("neighborhood_score"),
            },
            "risk": {
                "narrative": narratives.get("risk", ""),
                "compositeScore": prop["risk_score"],
                "topFlags": flags_text,
            },
            "financials": {
                "narrative": narratives.get("financials", ""),
                "capRate": prop["cap_rate"],
                "cashFlow": prop["cash_flow"],
                "cashOnCash": prop.get("cash_on_cash"),
                "rentEstMid": prop.get("rent_est_mid"),
                "rentConfidence": prop.get("rent_confidence", "Medium"),
            },
            "neighborhood": {
                "narrative": narratives.get("neighborhood", ""),
                "score": prop.get("neighborhood_score"),
                "name": prop.get("neighborhood"),
            },
        },
        "recommendation": _recommendation_from_deal_score(prop["deal_score"]),
        "disclaimer": _DISCLAIMER,
        "reportType": "cma",
    }

    report = Report(
        id=uuid.UUID(report_id),
        user_id=current_user.id,
        property_id=body.property_id,
        report_type="cma",
        content=content,
    )
    db.add(report)
    await db.flush()

    return content


# ── Property Brief ────────────────────────────────────────────────────────────

class PropertyBriefRequest(BaseModel):
    property_id: str
    agent_id: str | None = None
    client_name: str
    message: str | None = None


@router.post("/property-brief", status_code=201)
async def generate_property_brief(
    body: PropertyBriefRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    settings = get_settings()

    prop = _get_mock_property(body.property_id)
    if not prop:
        raise HTTPException(status_code=404, detail="Property not found")

    flags_plain = []
    severity_map = {"High": "⚠ ", "Medium": "• ", "Low": "ℹ "}
    for f in prop.get("risk_flags", [])[:3]:
        prefix = severity_map.get(f.get("severity", "Low"), "• ")
        flags_plain.append(prefix + f["label"])

    report_id = str(uuid.uuid4())
    content = {
        "reportId": report_id,
        "generatedAt": date.today().isoformat(),
        "reportType": "property_brief",
        "clientName": body.client_name,
        "agentMessage": body.message,
        "agent": {
            "name": current_user.name or "Your Agent",
            "email": current_user.email,
        },
        "property": {
            "id": prop["id"],
            "address": prop["address"],
            "city": prop["city"],
            "state": prop["state"],
            "zip": prop.get("zip", ""),
            "price": prop["price"],
            "beds": prop["beds"],
            "baths": prop["baths"],
            "sqft": prop["sqft"],
            "yearBuilt": prop.get("year_built"),
            "type": prop["type"],
            "dealScore": prop["deal_score"],
            "image": prop.get("image"),
        },
        "valuation": {
            "fairValueLow": prop["fair_value_low"],
            "fairValueHigh": prop["fair_value_high"],
            "confidence": prop.get("valuation_confidence", "Medium"),
            "priceVsFairValue": round(
                ((prop["price"] - (prop["fair_value_low"] + prop["fair_value_high"]) / 2)
                 / ((prop["fair_value_low"] + prop["fair_value_high"]) / 2) * 100), 1
            ) if prop["fair_value_low"] else 0,
        },
        "rentEstimate": {
            "low": prop.get("rent_est_low", 0),
            "mid": prop.get("rent_est_mid", 0),
            "high": prop.get("rent_est_high", 0),
            "confidence": prop.get("rent_confidence", "Medium"),
        },
        "topRiskFlags": flags_plain,
        "neighborhoodScore": prop.get("neighborhood_score"),
        "marketRegime": prop.get("market_regime", "Balanced"),
        "disclaimer": _DISCLAIMER,
    }

    report = Report(
        id=uuid.UUID(report_id),
        user_id=current_user.id,
        property_id=body.property_id,
        report_type="property_brief",
        content=content,
    )
    db.add(report)
    await db.flush()

    return content


# ── Public GET ────────────────────────────────────────────────────────────────

@router.get("/{report_id}")
async def get_report(
    report_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Report).where(Report.id == report_id)
    )
    report = result.scalar_one_or_none()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
    return report.content
